# This sudo thingy here will make sure that PHP 5.2 tests actually run on Travis
sudo: false

language: php

matrix:

    include:
        # Current $required_php_version for WordPress: 5.2.4
        # aliased to 5.2.17
        - php: '5.2'
          env: WP_VERSION=latest
        # aliased to a recent 5.6.x version
        - php: '5.6'
          env:
            - SNIFF=1
            - WP_VERSION=latest
            - WP_MULTISITE=0
        - php: '5.6'
          env:
            - SNIFF=1
            - WP_VERSION=latest
            - WP_MULTISITE=1
        # aliased to a recent 7.x version
        - php: '7.0'
          env: WP_VERSION=latest
        # aliased to a recent hhvm version
        - php: 'hhvm'
          env: WP_VERSION=latest

    allow_failures:
        - php: 'hhvm'

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit
