var program = require( 'commander' );

program
	.option( '--socketio-port [port]', 'Set Socket.io server port (default: 3000)', 3000 )
	.option( '--redis-host [host]', 'Set Redis server host (default: localhost)', 'localhost' )
	.option( '--redis-port [port]', 'Set Redis server port (default: 6379)', 6379 )
	.parse( process.argv );

var redis = require( 'socket.io-redis' );
var io = require( 'socket.io' )( program.socketioPort );

io.adapter( redis( { host: program.redisHost, port: program.redisPort } ) );

io.on( 'connection', function( socket ) {

	/**
	 * When a client connect it emits a 'post key' message
	 * containing the key of a post generated by WordPress.
	 * This key is used to add the client to a room named
	 * after the post key. This way only clients with permission
	 * to see the post will receive messages with updates
	 * to the Liveblog entries.
	 */
	socket.on( 'post key', function( post_key ) {
		socket.join( post_key );
	} );
} );
